### ISSUE TITLE
[App] Auth시나리오

### ISSUE THREAD

**Issue by heyman333** [HanRiverMeetup/HanRiverMeetup-react-native-iOS#6]
- 시나리오
   - 유저는 페이스북으로 회원가입을 진행한다.
   - 앱이 구동 될 때 앱에서 들고 있는 토큰을 서버에 verify를 요청한다.
   - 토큰이 유효하면 토큰을 리턴받고 바로 메인화면으로 입장 (서버에서는 토큰 시간을 확인하고 exp가 한시간이 안남았을 경우 새로운 토큰을 발급)
   - 앱에서 들고 있던 토큰이 유효하지 않으면 로그인화면으로 입장 
   - 로그인 후 페이스북토큰과 아이디어를 서버에 전달한다.
   - 서버는 유저테이블을 보고, 회원가입이 필요한 유저인지 바로 메인화면으로 가도 되는 유저인지 `status`를 준다.
     - {userStatus: "JOIN"}
     - {userStatus: "MAIN"}

**Comment by heyman333** [comment]
@TaerryKim @leemy0102 위대로 가능한지 확인좀 해주세요~

**Comment by TaerryKim** [comment]
* 시나리오

```
1. 페이스북으로 로그인을 요청하여 토큰 값과 id 값을 받아옴
2. 토큰 값과 id값을 서버로 전달하여 유효한지 체크
(만약 유효하다면 서버에서 유저 정보를 토큰정보와 같이 담아서 리턴. 이때 회원 가입이 되어있다면 nickname 값도 같이 리턴)

3. nickname값이 존재한다면 main 페이지로 이동, 없을 경우 회원 가입 페이지로 이동
4. nickname을 accessToken과 같이 전송하여 회원가입 -> 정상 가입되면 메인페이지로 이동

```

위와 같은 시나리오로 진행되며, 따로 스테이터스를 두지 않아도 될듯합니다.

(사실상 닉네임을 통해 온전히 확인되기 전까진 accessToken을 발급하면 안될듯한데.. 이건 추후 다시 고려해봐야할듯합니다)

**Comment by heyman333** [comment]
@TaerryKim 앱을 키자마자 서버에서 토큰을 verify하는 과정이 필요할거 같긴한데...
 - token이 Invalid하다 (또는 앱에 토큰이 없다) -> 로그인화면 -> 페북토큰 서버 전송 ->  유저 정보 전달 -> 닉네임이 있으면 메인으로 없으면 회원가입으로
 - token이 valid하다 -> 메인화면으로 
 - token이 valid하나 , 유효기간이 한시간 이내이다 -> 새로운 토큰 발급

**Comment by TaerryKim** [comment]
안드로이드의 경우 토큰은 매번 로그인 마다 갱신됩니다. 즉 페이스북으로 로그인이 되어있든 새로 로그인하든 항상 토큰을 새로 발급받게 되며, 앱을 껐다 켯을시에도 토큰을 재 갱신하게 됩니다. (앱 로컬에서는 따로 스토리지에 토큰을 보관하지 않음)

추가적으로 현재 토큰의 유효기간은 따로 정하지 않은 상태입니다.
